apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "privileged-container"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:   ["", "apps", "batch"]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods", "deployments", "daemonsets", "statefulsets", "replicasets", "cronjobs", "jobs"]
  variables:
    - name: podSpec
      expression: >
        object.kind == "Pod" ? object.spec : (
            object.kind in ["ReplicaSet", "Deployment", "DaemonSet", "StatefulSet", "Job"] ? object.spec.template.spec : (
                object.kind == "CronJob" ? object.spec.jobTemplate.spec.template.spec : null)
        )
    - name: allContainers
      expression: 'variables.podSpec.containers + variables.podSpec.?initContainers.orValue([])'
  validations:
    - expression: >
        variables.allContainers.all(c,
            c.?securityContext.?privileged.orValue(false) == false
        )
